language: python
python:
  - 3.6

services: sqlite3

env:
  - DJANGO_VERSION==2.0.1

before_install:
  - export DJANGO_SETTINGS_MODULE=mysite.settings
  - export PYTHONPATH=$HOME/builds/cavalryjim/mysite
  - export PIP_USE_MIRRORS=true

install:
  - pip install -q Django==$DJANGO_VERSION
  # - python setup.py -q install
  # - pip install -r requirements.txt
  # - pip install django==$DJANGO_VERSION --quiet
  # - pip install psycopg2 --quiet

before_script:
  #- psql -c "CREATE DATABASE mysite_test;" -U postgres
  #- python manage.py makemigrations
  - python manage.py migrate

script: python manage.py test
   #- python manage.py syncdb --noinput
   #- python manage.py test
