language: python
python:
  - 3.6

services: postgresql

env:
  - Django==2.0.1

before_install:
  - export DJANGO_SETTINGS_MODULE=mysite.settings
  - export PYTHONPATH=$HOME/builds/cavalryjim/mysite
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==2.0.1 --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE mysite;" -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script: #make
   #- python manage.py syncdb --noinput
   - python manage.py test
